### PR TITLE
feat: make it working

### PR DESCRIPTION
**Pull request by Helias**
It's still not working well, but at least now the players can join and enter to the arena correctly, but the arena ends when it starts for some checks that do not see any players inside the map (check in the module)

I made a related PR to the core to make this module compatible https://github.com/azerothcore/azerothcore-wotlk/pull/18679

### CODE REVIEW

**Comment by laasker** [comment]
Nice, i tested for a sec and now it works correctly as a 3v3. 
However, i tried setting ARENA_TEAM_SOLO_3v3 to 5 (5v5 slot), so players can see their and others players solo queue rating/score through inspect, but doing that makes the server worldserver close after loading the server. Any ideas why ?

**Comment by Helias** [comment]
No, but to should not use 5 for 3v3soloQ, 5 it's for standard 5v5

**Comment by laasker** [comment]
> No, but you should not use 5 for 3v3soloQ, 5 it's for standard 5v5

I know, but 5v5 is barely played. 
Anyway, after more tests i found that the statistics are not being saved after the game ends. 
They are recorded in the db log_arena_fights, but the personal and team rating/games stays at 0.
But it's not related to this PR, maybe we should create a bug report after the merge

**Comment by Helias** [comment]
ok, I would like to clean the code, give it a try to enable 2v2 and 5v5 and fix the optional `FilterTalents`, for now it's mandatory, otherwise it does not work properly.

the arena 1v1 I think is not necessary due to the mod-arena-1v1, but if it will be feasible, I will enable also that

**Comment by Helias** [comment]
I made the config optional, I could remove the arena 1v1 conf and merge this PR consider that this module now reached "stable" version

**Comment by mynew** [comment]
There is no record of the number of players queuing and the number of wins in the arena_team table.

**Comment by mynew** [comment]
There is no record of the number of players queuing and the number of wins in the arena_team table.

**Comment by pangolp** [comment]
> There is no record of the number of players queuing and the number of wins in the arena_team table.

The module is under development, and although we have a stable version of it, it may not be 100% functional. It is something that we are doing, in the free time we have, but since it is free code, anyone could collaborate, and we have no problem reviewing the code and, in any case, merging it, if it modifies or changes any mechanics. Otherwise, we will have to wait for the time available to the developers who want to collaborate with it. If there is any error, can you please review the issues that are found, and if within them, what you are doing is not mentioned, I ask you to create one so that we are aware of it. Thank you. https://github.com/azerothcore/mod-arena-3v3-solo-queue/issues

**Pull request merged**
